//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENLAI
    {
        public string MaBienLai { get; set; }
        public string BienLaiHocVien { get; set; }
        public Nullable<System.DateTime> NgayInBienLai { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
    }
}
