//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTrungTamAnhVanEntities1 : DbContext
    {
        public QuanLyTrungTamAnhVanEntities1()
            : base("name=QuanLyTrungTamAnhVanEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOLUU> BAOLUUs { get; set; }
        public virtual DbSet<BIENLAI> BIENLAIs { get; set; }
        public virtual DbSet<CHUNGCHI> CHUNGCHIs { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<HOCVIEN> HOCVIENs { get; set; }
        public virtual DbSet<KETQUAHOCTAP> KETQUAHOCTAPs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<PHANCONG> PHANCONGs { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOCs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THOIGIANHOC> THOIGIANHOCs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    }
}
