//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAHOCTAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KETQUAHOCTAP()
        {
            this.HOCVIENs = new HashSet<HOCVIEN>();
        }
    
        public string MaKQ { get; set; }
        public string diemnguphap { get; set; }
        public string diemgiaotiep { get; set; }
        public string diemchuyencan { get; set; }
        public string diemkynang { get; set; }
        public string diembaitap { get; set; }
        public string diemdinhky { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCVIEN> HOCVIENs { get; set; }
    }
}
