//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.HOCVIENs = new HashSet<HOCVIEN>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string SiSo { get; set; }
        public string MaKM { get; set; }
        public string MaPhong { get; set; }
        public string MaChungChi { get; set; }
        public string MaThoiGian { get; set; }
    
        public virtual CHUNGCHI CHUNGCHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCVIEN> HOCVIENs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
        public virtual THOIGIANHOC THOIGIANHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
