//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public string MaGV { get; set; }
        public string MaLop { get; set; }
        public string Phong { get; set; }
        public Nullable<System.DateTime> ngayday { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
    }
}
