//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlitrungtamngoaingu.Dataaccesslayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG
    {
        public string MaHV { get; set; }
        public string BaoLuu { get; set; }
        public string SoLanCoMat { get; set; }
        public string SoLanVangMat { get; set; }
    
        public virtual BAOLUU BAOLUU1 { get; set; }
        public virtual HOCVIEN HOCVIEN { get; set; }
    }
}
